### ISSUE TITLE
Error when trying to run ASimulator in terminal with run_asimulator.sh

### ISSUE THREAD

**Issue by NormanRog** [CGAT-Group/DICAST#3]
Hi Quirin,
I received the following error message when I tried to run ASimulatoR with the run_asimulator.sh script.

finished loading superset

assign variants to supersets...
create splicing variants and annotation. This may take a while...
finished creating splicing variants and annotation

exporting gtf for read simulation...
Error in file(file, ifelse(append, "a", "w")) :
cannot open the connection
Calls: do.call ... -> export -> export -> .local -> cat -> file
In addition: Warning messages:
1: In mclapply(X, FUN, ..., mc.cores = mc.cores, mc.preschedule = mc.preschedule, :
scheduled cores 2, 3, 4, 10, 11, 18 did not deliver results, all values of the jobs will be affected
2: In file(file, ifelse(append, "a", "w")) :
cannot open file '/output//splicing_variants.gtf': Permission denied
Execution halted
mv: cannot stat '/mnt/301e9812-51b9-4539-a38f-225aa84a1d0b/DICAST/DICAST/src/ASimulatoR/out/*gtf': No such file or directory
mv: cannot stat '/mnt/301e9812-51b9-4539-a38f-225aa84a1d0b/DICAST/DICAST/src/ASimulatoR/out/*gff3': No such file or directory
ls: cannot access '/mnt/301e9812-51b9-4539-a38f-225aa84a1d0b/DICAST/DICAST/src/ASimulatoR/out/*fastq': No such file or directory

**Comment by quirinmanz** [comment]
Please check [this answer](https://github.com/CGAT-Group/DICAST/issues/2#issuecomment-1145004211) in issue #2

**Comment by amitfenn** [comment]
Thanks Quirin, This works. :)
