### ISSUE TITLE
DICAST GUI crashes when clicking "Select custom Snakefile"

### ISSUE THREAD

**Issue by KarmaChild** [CGAT-Group/DICAST#5]
Hello, 

I'm very new to DICAST and I'm trying to run the GUI, after selecting the working directory, when I press the "Browse" button to select the custom Snakefile, the GUI immediately crashes with this message - 

(base) adi@Adithyas-Air DICAST % conda activate dicast-snakemake
(dicast-snakemake) adi@Adithyas-Air DICAST % python gui/dicast.py
Traceback (most recent call last):
  File "/Users/adi/opt/DICAST/gui/dicast.py", line 58, in <lambda>
    self.snake_button.clicked.connect(lambda: self.set_snake_file(self.select_snakefile_label))
  File "/Users/adi/opt/DICAST/gui/dicast.py", line 354, in set_snake_file
    self.custom_snakefile_full_path = on_button_get_file_path_clicked(label, self.wd_folder_full_path)
  File "/Users/adi/opt/DICAST/gui/dicast_config_setter.py", line 67, in on_button_get_file_path_clicked
    dialog = FileDialog(True)
  File "/Users/adi/opt/DICAST/gui/dicast_config_setter.py", line 17, in __init__
    self.forward_button.blockSignals(True)
AttributeError: 'NoneType' object has no attribute 'blockSignals'
zsh: abort      python gui/dicast.py

Would appreciate your help a lot! Thanks!

**Comment by amitfenn** [comment]
Sorry, K,

https://dicast.readthedocs.io/en/master/get-started/run/gui.html
shows that this approach is depreciated. If you must use it, please consider the solutions [here](https://github.com/CGAT-Group/DICAST/issues/1#issue-1096428613):

I would recommend using the tried and tested approach:
https://dicast.readthedocs.io/en/master/get-started/run/dicast-cli.html.

Alternatively, if you think you may not need simulations or all of the pipeline, you could use this approach:
https://dicast.readthedocs.io/en/master/get-started/run/one_tool.html,

Best wishes,
Amit.
